kind: pipeline
name: build and publish
steps:
  - name: build
    image: archxlinux/archxlinux
    pull: always
    privileged: true
    commands:
      - yes|pacman -Sy base-devel 
      - ./build.sh 
    volumes:
    - name: build
      path: /tmp/build 
    - name: iso
      path: /tmp/iso 
  - name: login
    environment:
      GITHUB_TOKEN:
        from_secret: git_token
    image: ghcr.io/supportpal/github-gh-cli 
    commands: 
      - gh auth login --hostname github.com || true
      - gh release create $(git log -1 --pretty='%ad' --date=format:'%Y.%m.%d') /tmp/iso/*
    volumes:
    - name: build
      path: /tmp/build 
    - name: iso
      path: /tmp/iso 

volumes:
- name: build
  temp: {}
- name: iso
  temp: {}
- name: temp-repo
  temp: {}
