kind: pipeline
name: build and publish
steps:
  - name: build
    image: archxlinux/iso
    pull: always
    privileged: true
    commands:
      - bash /entrypoint.sh
    volumes:
    - name: build
      path: /tmp/build 
    - name: iso
      path: /tmp/iso 
  - name: publish-github
    image: plugins/github-release
    volumes:
      - name: iso
        path: /tmp/iso
    settings:
      api_key:
        from_secret: github_token
      files: /tmp/iso/*iso
      prerelease: yes

volumes:
- name: build
  temp: {}
- name: iso
  temp: {}
- name: temp-repo
  temp: {}
